@baseUrl =  http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAaWFzaGNodWsucnUiLCJpZCI6IjYzNTUzNTQxYTJmMGRhZTBmNWY0ODIxNiIsImlhdCI6MTY2NjgyNDA5NywiZXhwIjoxNjY2OTk2ODk3fQ.HM_AFX4Ge6EFww1I5Mmn48gP1mgyGc5u9tizvZbPUz8
@offerId = 635535eea2f0dae0f5f4821a
@offerIdForDelete = 635546b98fc542f0f505a3ef

# Тестовые данные
GET http://localhost:3123/api HTTP/1.1

###

## Создание нового предложения (2.1)
POST {{baseUrl}}/offers HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "name": "The Luxury Heart32",
  "description": "Fashion cozy house in the heart of Amsterdam",
  "date": "2022-06-24T14:00:00.246Z",
  "city": "Amsterdam",
  "photos": ["apartment-01.jpg", "apartment-02.jpg", "apartment-03.jpg","apartment-01.jpg", "apartment-02.jpg", "apartment-03.jpg"],
  "isPremium": true,
  "rating": 4,
  "type": "apartment",
  "rooms": 2,
  "guests": 2,
  "price": 5000,
  "features": ["Air conditioning"],
  "userId": "63342ed08909c539c45f3e93",
  "comments": 0,
  "coordinates": ["52.370216", "4.895168"]
}

###

## Редактирование предложения (2.2)
PATCH {{baseUrl}}/offers/{{offerId}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "name": "New The Test Studio Super"
}

###

## Удаление предложения (2.3)
DELETE  {{baseUrl}}/offers/{{offerIdForDelete}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###

## Получение списка предложений по аренде (2.4)
GET {{baseUrl}}/offers HTTP/1.1
Content-Type: application/json

###

## Получение детальной информации о предложении (2.5)
GET {{baseUrl}}/offers/{{offerId}} HTTP/1.1
Content-Type: application/json

###

## Получение списка комментариев для предложения (2.6)
GET {{baseUrl}}/offers/{{offerId}}/comments HTTP/1.1
Content-Type: application/json

###

## Добавление комментария для предложения (2.7)
POST {{baseUrl}}/comments HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "text": "Some comment",
  "rating": 4,
  "offerId": "635535eea2f0dae0f5f4821a",
  "userId": "63553541a2f0dae0f5f48216"
}

###

## Создание нового пользователя (2.8)
POST {{baseUrl}}/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Vitalii",
  "email": "test@iashchuk.ru",
  "type": "pro",
  "password": "123456"

}

###

## Вход в закрытую часть приложения (2.9)
POST {{baseUrl}}/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@iashchuk.ru",
  "password": "123456"
}

###

## Проверка состояния пользователя (2.10)
GET {{baseUrl}}/users/login HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###

## Обновление аватара пользователя
POST {{baseUrl}}/users/63553541a2f0dae0f5f48216/avatar HTTP/1.1
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-max.jpg"
Content-Type: image/jpeg

< ./markup/img/avatar-max.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Обновление превью предложения
POST {{baseUrl}}/offers/{{offerId}}/preview HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: {{token}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="preview"; filename="amsterdam@2x.jpg"
Content-Type: image/jpeg

< ./markup/img/amsterdam@2x.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###


