export const DEFAULT_OFFER_COUNT = 60;
export const DEFAULT_OFFER_PREVIEW_NAME = 'amsterdam.jpg';

export const OFFER_CONSTRAINT = {
  NAME_LENGTH_MIN: 10,
  NAME_LENGTH_MAX: 100,
  DESCRIPTION_LENGTH_MIN: 20,
  DESCRIPTION_LENGTH_MAX: 1024,
  ROOMS_COUNT_MIN: 1,
  ROOMS_COUNT_MAX: 8,
  RATING_MIN: 1,
  RATING_MAX: 5,
  PHOTOS_COUNT: 6,
  GUESTS_COUNT_MIN: 1,
  GUESTS_COUNT_MAX: 10,
  PRICE_MIN: 100,
  PRICE_MAX: 100000,
} as const;
